name: Form API Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-form-api:
    runs-on: ubuntu-latest
    steps:
      - name: テスト用APIリクエスト
        run: |
          response=$(curl -s -X POST https://suumo-backend.onrender.com/api/send \
            -H "Content-Type: application/json" \
            -d '{"type":"contact","name":"テスト","email":"test@example.com","message":"自動テスト送信"}')
          echo "API Response: $response"
          echo "$response" | grep 'success' | grep 'true' 